import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {data.map(ev => {
          return (
            <Link key={ev.id} href={`/events/${ev.id}`}>
              <Image src={ev.image} alt={ev.title} width="200" height="160" />
              <h2>{ev.title}</h2>
            </Link>
          );
        })}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const data = await import('@/data/data.json');
  return {
    props: { data: data.events_categories }
  };
}

export default Home;